apiVersion: v1
kind: Pod
metadata:
  name: my-application
spec:
  containers:
  - name: my-app-container
    image: my-app:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
