apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
      - name: example-job-container
        image: example:latest
        command: ["your-command"]
      restartPolicy: Never
  backoffLimit: 4
