apiVersion: v1
kind: Pod
metadata:
  name: demopod
spec:
  containers:
  - name: demo-container
    image: gcr.io/vshpelyk-devops/demo:v1.0.0
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
