apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: demo-container
    image: gcr.io/vshpelyk-devops/demo:v1.0.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /var/lib/demo
      name: demo-volume
  volumes:
  - name: demo-volume
    emptyDir: {}
